# docker-compose.yml

version: '3.8'
services:
    ros_dev_env:
        container_name: openbot_ros
        build: ./
        environment:
            - DISPLAY=novnc:0.0
        networks:
            - x11
        stdin_open: true
        tty: true
        ports:
            - "127.0.0.1:2222:22"
            - "9090:9090"
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
            
    novnc:
        #  novnc The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requeste
        # image: theasp/novnc:latest
        container_name: novnc
        build: ./docker-novnc
        environment:
            - DISPLAY_WIDTH=2560
            - DISPLAY_HEIGHT=1440
        ports:
            - "8080:8080"
        networks:
            - x11
        restart: on-failure

    # amd64
    # webviz:
    #   image: cruise/webviz
    #   ports:
    #         - "8081:8080"
    #   networks:
    #       - x11
networks:
    x11:
