# docker-compose.yml
version: '3.8'
services:
  ros_dev_env:
    container_name: ROS2_Humble
    build: ./
    volumes:
      - ../../:/ros2_ws/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - /tmp/.docker.xauth:/tmp/.docker.xauth
    environment:
      - DISPLAY=:10.0
      - QT_X11_NO_MITSHM=1
      # - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=all # Ensures all NVIDIA capabilities are enabled
      - NVIDIA_VISIBLE_DEVICES=all # Makes all GPUs visible to the container
    devices:
      - /dev/dri:/dev/dri # Maps video device resources for GPU access
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    runtime: nvidia
    privileged: true # Gives the container privileged access
    network_mode: host # Allows the container to share the host network
