turtlebot3_fake_node:
  ros__parameters:
    wheels:
      separation: 0.4838  # 双轮距离，单位：米
      radius: 0.046735   # 轮子半径，单位：米

    joint_states_frame: "base_footprint"
    odom_frame: "odom"
    base_frame: "base_footprint"
